language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly


matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - mysql -e 'create database test;'

script: phpunit